---
- name: install git on ubuntu servers
  hosts: Ubuntu
  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
- name: install git on Redhat servers
  hosts: Redhat
  tasks:
    - name: install git
      yum:
        name: git
        state: present
        update_cache: yes
...
