---
- name: implementing playscope variables
  hosts: all
  vars:
    - a: tomcat10
    - b: present
    - c: yes
  tasks:
    - name: install tomcat10
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
