---
- name: configuring apache2/httpd on both redhat and ubuntu servers
  hosts: all
  tasks:
    - name: install apache2 0n ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install httpd on redhat servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "Intelliq"
        dest: /var/www/html/index.html
    - name: restart apache2 on  ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restart httpd on redhat servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: check url response of both the servers
      uri:
        url: "{{item}}"
      with_items:
        - http://172.31.7.112
        - http://172.31.29.10

...
