---
- name: install and uninstall softwares
  hosts: all
  tasks:
    - name: install and uninstall software apps
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: yes}
        - {a: maven,b: present,c: no}
...
          
