---
- name: create users and copy files into user home dir
  hosts: all
  tasks:
    - name: create mutltipe users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: kali,b: intelliqit,c: /tmp/kali}
        - {a: suma,b: devops,c: /home/suma}
    - name: copy file user home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
        owner: "{{item.c}}"
        group: "{{item.d}}"
        mode: "{{item.e}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/kali,c: kali,d: suma,e: 770}
        - {a: /etc/group,b: /home/suma,c: suma,d: kali,e: 761}
...
